# Site settings
title: Tom Shen
email: tom@shen.io
description: >
  I drink coffee, write code, and try to read lots of books.
baseurl: ""
permalink: none
url: "http://www.tomshen.me"
twitter_username: tomshen
github_username:  tomshen

# Build settings
markdown: kramdown
