# Site settings
title: Tom Shen
email: tom@shen.io
description: > # this means to ignore newlines until "baseurl:"
  Web developer & CMU student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tomshen.me" # the base hostname & protocol for your site
github_username:  tomshen

# Build settings
highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty
