# Site settings
title: Tom Shen
email: tom@shen.io
description: >
  The personal site of Tom Shen, web developer.
baseurl: ""
url: "http://www.tomshen.me"
twitter_username: tomshen
github_username:  tomshen

# Build settings
markdown: kramdown
